"""chip windows

Revision ID: 3e49dc28fb10
Revises: 524cb5172336
Create Date: 2026-08-31 01:12:35.021808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e49dc28fb10'
down_revision: Union[str, None] = '524cb5172336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chip_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('chip_type', sa.String(length=20), nullable=False),
    sa.Column('start_event', sa.Integer(), nullable=False),
    sa.Column('stop_event', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'start_event', name='uq_chip_window')
    )
    op.create_index(op.f('ix_chip_windows_name'), 'chip_windows', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chip_windows_name'), table_name='chip_windows')
    op.drop_table('chip_windows')
    # ### end Alembic commands ###
