"""player photo code

Revision ID: 42145e9a9170
Revises: ae747c2df900
Create Date: 2026-08-25 15:30:22.996978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42145e9a9170'
down_revision: Union[str, None] = 'ae747c2df900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edited: autogenerate omits server_default, which fails on the 610
    # existing player rows. The real codes arrive on the next sync.
    op.add_column('players', sa.Column('code', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'code')
    # ### end Alembic commands ###
