"""sync state

Revision ID: 4462aaf15fb2
Revises: 3e49dc28fb10
Create Date: 2026-10-02 15:31:42.801187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4462aaf15fb2'
down_revision: Union[str, None] = '3e49dc28fb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_state',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    # ### end Alembic commands ###
