"""telegram notifications: opt-in per manager

Revision ID: 524cb5172336
Revises: 42145e9a9170
Create Date: 2026-08-30 18:07:11.545155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '524cb5172336'
down_revision: Union[str, None] = '42145e9a9170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_links',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_telegram_links_expires_at'), 'telegram_links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_telegram_links_fpl_entry_id'), 'telegram_links', ['fpl_entry_id'], unique=False)
    op.add_column('alerts', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alerts_notified_at'), 'alerts', ['notified_at'], unique=False)
    op.add_column('tracked_managers', sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))
    op.add_column('tracked_managers', sa.Column('telegram_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tracked_managers', sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tracked_managers_telegram_chat_id'), 'tracked_managers', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_managers_telegram_chat_id'), table_name='tracked_managers')
    op.drop_column('tracked_managers', 'telegram_linked_at')
    op.drop_column('tracked_managers', 'telegram_enabled')
    op.drop_column('tracked_managers', 'telegram_chat_id')
    op.drop_index(op.f('ix_alerts_notified_at'), table_name='alerts')
    op.drop_column('alerts', 'notified_at')
    op.drop_index(op.f('ix_telegram_links_fpl_entry_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_expires_at'), table_name='telegram_links')
    op.drop_table('telegram_links')
    # ### end Alembic commands ###
