"""fixture finished_provisional and minutes

Revision ID: 7dbc95549525
Revises: 85aa4e3c095f
Create Date: 2026-08-24 15:49:25.500220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7dbc95549525'
down_revision: Union[str, None] = '85aa4e3c095f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixtures', sa.Column('finished_provisional', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('fixtures', sa.Column('minutes', sa.SmallInteger(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_fixtures_finished_provisional'), 'fixtures', ['finished_provisional'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixtures_finished_provisional'), table_name='fixtures')
    op.drop_column('fixtures', 'minutes')
    op.drop_column('fixtures', 'finished_provisional')
    # ### end Alembic commands ###
