"""projections, scoring rules, team strength, gw stats

Revision ID: 85aa4e3c095f
Revises: d47ee5a5797f
Create Date: 2026-08-24 15:40:40.048488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '85aa4e3c095f'
down_revision: Union[str, None] = 'd47ee5a5797f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('dc_threshold_def', sa.SmallInteger(), nullable=False),
    sa.Column('dc_threshold_mid_fwd', sa.SmallInteger(), nullable=False),
    sa.Column('saves_per_point', sa.SmallInteger(), nullable=False),
    sa.Column('goals_conceded_per_penalty', sa.SmallInteger(), nullable=False),
    sa.Column('long_play_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rules_is_active'), 'scoring_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_scoring_rules_season'), 'scoring_rules', ['season'], unique=False)
    op.create_table('team_strength',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('matches_played', sa.SmallInteger(), nullable=False),
    sa.Column('attack_home', sa.Float(), nullable=False),
    sa.Column('attack_away', sa.Float(), nullable=False),
    sa.Column('defence_home', sa.Float(), nullable=False),
    sa.Column('defence_away', sa.Float(), nullable=False),
    sa.Column('observed_scored_per_match', sa.Float(), nullable=False),
    sa.Column('observed_conceded_per_match', sa.Float(), nullable=False),
    sa.Column('prior_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'model_version', name='uq_team_strength')
    )
    op.create_index(op.f('ix_team_strength_model_version'), 'team_strength', ['model_version'], unique=False)
    op.create_index(op.f('ix_team_strength_team_id'), 'team_strength', ['team_id'], unique=False)
    op.create_table('player_gameweek_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('opponent_team', sa.Integer(), nullable=True),
    sa.Column('was_home', sa.Boolean(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bps', sa.Integer(), nullable=False),
    sa.Column('defensive_contribution', sa.Integer(), nullable=False),
    sa.Column('expected_goals', sa.Float(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('expected_goals_conceded', sa.Float(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek_id', 'fixture_id', name='uq_pgs_player_gw_fixture')
    )
    op.create_index(op.f('ix_player_gameweek_stats_gameweek_id'), 'player_gameweek_stats', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_player_gameweek_stats_player_id'), 'player_gameweek_stats', ['player_id'], unique=False)
    op.create_table('projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('xpts', sa.Float(), nullable=False),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('expected_minutes', sa.Float(), nullable=False),
    sa.Column('p_start', sa.Float(), nullable=False),
    sa.Column('p_appear', sa.Float(), nullable=False),
    sa.Column('p_60_plus', sa.Float(), nullable=False),
    sa.Column('availability_multiplier', sa.Float(), nullable=False),
    sa.Column('xpts_appearance', sa.Float(), nullable=False),
    sa.Column('xpts_goals', sa.Float(), nullable=False),
    sa.Column('xpts_assists', sa.Float(), nullable=False),
    sa.Column('xpts_clean_sheet', sa.Float(), nullable=False),
    sa.Column('xpts_goals_conceded', sa.Float(), nullable=False),
    sa.Column('xpts_saves', sa.Float(), nullable=False),
    sa.Column('xpts_defensive_contribution', sa.Float(), nullable=False),
    sa.Column('xpts_bonus', sa.Float(), nullable=False),
    sa.Column('xpts_cards', sa.Float(), nullable=False),
    sa.Column('xpts_penalties', sa.Float(), nullable=False),
    sa.Column('fixture_count', sa.SmallInteger(), nullable=False),
    sa.Column('expected_team_goals', sa.Float(), nullable=False),
    sa.Column('expected_team_conceded', sa.Float(), nullable=False),
    sa.Column('custom_fdr', sa.Float(), nullable=False),
    sa.Column('opponents', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek_id', 'model_version', name='uq_projection')
    )
    op.create_index(op.f('ix_projections_gameweek_id'), 'projections', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_projections_model_version'), 'projections', ['model_version'], unique=False)
    op.create_index(op.f('ix_projections_player_id'), 'projections', ['player_id'], unique=False)
    # NOTE: hand-edited. Autogenerate emitted these NOT NULL columns without a
    # server_default, which fails on the existing 609 player rows. server_default
    # backfills them; the model's Python-side default takes over on new inserts.
    _NOT_NULL_NUMERIC = [
        ('own_goals', sa.Integer()),
        ('penalties_saved', sa.Integer()),
        ('penalties_missed', sa.Integer()),
        ('expected_goals_conceded', sa.Float()),
        ('clearances_blocks_interceptions', sa.Integer()),
        ('recoveries', sa.Integer()),
        ('tackles', sa.Integer()),
        ('defensive_contribution', sa.Integer()),
        ('starts_per_90', sa.Float()),
        ('expected_goals_per_90', sa.Float()),
        ('expected_assists_per_90', sa.Float()),
        ('expected_goals_conceded_per_90', sa.Float()),
        ('goals_conceded_per_90', sa.Float()),
        ('clean_sheets_per_90', sa.Float()),
        ('saves_per_90', sa.Float()),
        ('defensive_contribution_per_90', sa.Float()),
        ('points_per_game', sa.Float()),
        ('price_change_percent', sa.Float()),
        ('price_change_hourly_rate', sa.Integer()),
        ('cost_change_event', sa.Integer()),
        ('cost_change_start', sa.Integer()),
    ]
    for _name, _type in _NOT_NULL_NUMERIC:
        op.add_column('players', sa.Column(_name, _type, nullable=False, server_default='0'))

    # Nullable columns need no backfill
    op.add_column('players', sa.Column('penalties_order', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('corners_freekicks_order', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('direct_freekicks_order', sa.SmallInteger(), nullable=True))
    op.add_column('players', sa.Column('price_change_projections', sa.JSON(), nullable=True))
    op.add_column('players', sa.Column('price_change_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'cost_change_start')
    op.drop_column('players', 'cost_change_event')
    op.drop_column('players', 'price_change_locked_until')
    op.drop_column('players', 'price_change_projections')
    op.drop_column('players', 'price_change_hourly_rate')
    op.drop_column('players', 'price_change_percent')
    op.drop_column('players', 'direct_freekicks_order')
    op.drop_column('players', 'corners_freekicks_order')
    op.drop_column('players', 'penalties_order')
    op.drop_column('players', 'points_per_game')
    op.drop_column('players', 'defensive_contribution_per_90')
    op.drop_column('players', 'saves_per_90')
    op.drop_column('players', 'clean_sheets_per_90')
    op.drop_column('players', 'goals_conceded_per_90')
    op.drop_column('players', 'expected_goals_conceded_per_90')
    op.drop_column('players', 'expected_assists_per_90')
    op.drop_column('players', 'expected_goals_per_90')
    op.drop_column('players', 'starts_per_90')
    op.drop_column('players', 'defensive_contribution')
    op.drop_column('players', 'tackles')
    op.drop_column('players', 'recoveries')
    op.drop_column('players', 'clearances_blocks_interceptions')
    op.drop_column('players', 'expected_goals_conceded')
    op.drop_column('players', 'penalties_missed')
    op.drop_column('players', 'penalties_saved')
    op.drop_column('players', 'own_goals')
    op.drop_index(op.f('ix_projections_player_id'), table_name='projections')
    op.drop_index(op.f('ix_projections_model_version'), table_name='projections')
    op.drop_index(op.f('ix_projections_gameweek_id'), table_name='projections')
    op.drop_table('projections')
    op.drop_index(op.f('ix_player_gameweek_stats_player_id'), table_name='player_gameweek_stats')
    op.drop_index(op.f('ix_player_gameweek_stats_gameweek_id'), table_name='player_gameweek_stats')
    op.drop_table('player_gameweek_stats')
    op.drop_index(op.f('ix_team_strength_team_id'), table_name='team_strength')
    op.drop_index(op.f('ix_team_strength_model_version'), table_name='team_strength')
    op.drop_table('team_strength')
    op.drop_index(op.f('ix_scoring_rules_season'), table_name='scoring_rules')
    op.drop_index(op.f('ix_scoring_rules_is_active'), table_name='scoring_rules')
    op.drop_table('scoring_rules')
    # ### end Alembic commands ###
