"""recommendation snapshots and outcomes

Revision ID: 956a4d4ee391
Revises: e11e6ed284ff
Create Date: 2026-08-25 03:00:10.366216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '956a4d4ee391'
down_revision: Union[str, None] = 'e11e6ed284ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_entry_id', 'gameweek_id', 'kind', 'model_version', name='uq_rec_snapshot')
    )
    op.create_index('ix_rec_snapshot_entry_gw', 'recommendation_snapshots', ['fpl_entry_id', 'gameweek_id'], unique=False)
    op.create_index(op.f('ix_recommendation_snapshots_created_at'), 'recommendation_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_snapshots_fpl_entry_id'), 'recommendation_snapshots', ['fpl_entry_id'], unique=False)
    op.create_index(op.f('ix_recommendation_snapshots_gameweek_id'), 'recommendation_snapshots', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_recommendation_snapshots_kind'), 'recommendation_snapshots', ['kind'], unique=False)
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('regret', sa.Float(), nullable=False),
    sa.Column('override_delta', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['recommendation_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', name='uq_outcome_snapshot')
    )
    op.create_index('ix_outcome_entry_gw', 'recommendation_outcomes', ['fpl_entry_id', 'gameweek_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_fpl_entry_id'), 'recommendation_outcomes', ['fpl_entry_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_gameweek_id'), 'recommendation_outcomes', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_kind'), 'recommendation_outcomes', ['kind'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_scored_at'), 'recommendation_outcomes', ['scored_at'], unique=False)
    op.create_index(op.f('ix_recommendation_outcomes_snapshot_id'), 'recommendation_outcomes', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_outcomes_snapshot_id'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_scored_at'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_kind'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_gameweek_id'), table_name='recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_outcomes_fpl_entry_id'), table_name='recommendation_outcomes')
    op.drop_index('ix_outcome_entry_gw', table_name='recommendation_outcomes')
    op.drop_table('recommendation_outcomes')
    op.drop_index(op.f('ix_recommendation_snapshots_kind'), table_name='recommendation_snapshots')
    op.drop_index(op.f('ix_recommendation_snapshots_gameweek_id'), table_name='recommendation_snapshots')
    op.drop_index(op.f('ix_recommendation_snapshots_fpl_entry_id'), table_name='recommendation_snapshots')
    op.drop_index(op.f('ix_recommendation_snapshots_created_at'), table_name='recommendation_snapshots')
    op.drop_index('ix_rec_snapshot_entry_gw', table_name='recommendation_snapshots')
    op.drop_table('recommendation_snapshots')
    # ### end Alembic commands ###
