"""squad overrides

Revision ID: ae747c2df900
Revises: b2530dab0bd9
Create Date: 2026-08-25 15:06:26.127378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae747c2df900'
down_revision: Union[str, None] = 'b2530dab0bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squad_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=False),
    sa.Column('player_ids', sa.JSON(), nullable=False),
    sa.Column('bank', sa.Integer(), nullable=False),
    sa.Column('free_transfers', sa.Integer(), nullable=False),
    sa.Column('transfers_applied', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_entry_id', 'gameweek_id', name='uq_squad_override')
    )
    op.create_index(op.f('ix_squad_overrides_fpl_entry_id'), 'squad_overrides', ['fpl_entry_id'], unique=False)
    op.create_index(op.f('ix_squad_overrides_gameweek_id'), 'squad_overrides', ['gameweek_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squad_overrides_gameweek_id'), table_name='squad_overrides')
    op.drop_index(op.f('ix_squad_overrides_fpl_entry_id'), table_name='squad_overrides')
    op.drop_table('squad_overrides')
    # ### end Alembic commands ###
