"""tracked managers and price change baseline

Revision ID: b2530dab0bd9
Revises: 956a4d4ee391
Create Date: 2026-08-25 14:43:38.340020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2530dab0bd9'
down_revision: Union[str, None] = '956a4d4ee391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_managers',
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fpl_entry_id')
    )
    op.create_index(op.f('ix_tracked_managers_alerts_enabled'), 'tracked_managers', ['alerts_enabled'], unique=False)
    # Hand-edited: autogenerate omits server_default, which fails on the
    # existing snapshot rows.
    op.add_column('player_availability_snapshots', sa.Column('price_change_percent', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_availability_snapshots', 'price_change_percent')
    op.drop_index(op.f('ix_tracked_managers_alerts_enabled'), table_name='tracked_managers')
    op.drop_table('tracked_managers')
    # ### end Alembic commands ###
