"""initial fpl tables

Revision ID: d47ee5a5797f
Revises: 
Create Date: 2026-08-24 15:15:05.892488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd47ee5a5797f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('deadline_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_next', sa.Boolean(), nullable=False),
    sa.Column('is_previous', sa.Boolean(), nullable=False),
    sa.Column('average_entry_score', sa.Integer(), nullable=False),
    sa.Column('highest_score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gameweeks_is_current'), 'gameweeks', ['is_current'], unique=False)
    op.create_index(op.f('ix_gameweeks_is_next'), 'gameweeks', ['is_next'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.SmallInteger(), nullable=False),
    sa.Column('strength_overall_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_overall_away', sa.SmallInteger(), nullable=False),
    sa.Column('strength_attack_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_attack_away', sa.SmallInteger(), nullable=False),
    sa.Column('strength_defence_home', sa.SmallInteger(), nullable=False),
    sa.Column('strength_defence_away', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameweek_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_h', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.Integer(), nullable=False),
    sa.Column('team_h_score', sa.SmallInteger(), nullable=True),
    sa.Column('team_a_score', sa.SmallInteger(), nullable=True),
    sa.Column('team_h_difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('team_a_difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweeks.id'], ),
    sa.ForeignKeyConstraint(['team_a'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_h'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_gameweek_id'), 'fixtures', ['gameweek_id'], unique=False)
    op.create_index(op.f('ix_fixtures_team_a'), 'fixtures', ['team_a'], unique=False)
    op.create_index(op.f('ix_fixtures_team_h'), 'fixtures', ['team_h'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('web_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('selected_by_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('chance_of_playing_this_round', sa.SmallInteger(), nullable=True),
    sa.Column('chance_of_playing_next_round', sa.SmallInteger(), nullable=True),
    sa.Column('news', sa.Text(), nullable=False),
    sa.Column('ep_this', sa.Float(), nullable=False),
    sa.Column('ep_next', sa.Float(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Integer(), nullable=False),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('bps', sa.Integer(), nullable=False),
    sa.Column('influence', sa.Float(), nullable=False),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('threat', sa.Float(), nullable=False),
    sa.Column('ict_index', sa.Float(), nullable=False),
    sa.Column('expected_goals', sa.Float(), nullable=False),
    sa.Column('expected_assists', sa.Float(), nullable=False),
    sa.Column('expected_goal_involvements', sa.Float(), nullable=False),
    sa.Column('transfers_in_event', sa.Integer(), nullable=False),
    sa.Column('transfers_out_event', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_status'), 'players', ['status'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_index(op.f('ix_players_web_name'), 'players', ['web_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_web_name'), table_name='players')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_status'), table_name='players')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_fixtures_team_h'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_team_a'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_gameweek_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_table('teams')
    op.drop_index(op.f('ix_gameweeks_is_next'), table_name='gameweeks')
    op.drop_index(op.f('ix_gameweeks_is_current'), table_name='gameweeks')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
