"""availability events, snapshots, alerts

Revision ID: e11e6ed284ff
Revises: 7dbc95549525
Create Date: 2026-08-24 18:40:34.367079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e11e6ed284ff'
down_revision: Union[str, None] = '7dbc95549525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('status_before', sa.String(length=1), nullable=True),
    sa.Column('status_after', sa.String(length=1), nullable=True),
    sa.Column('availability_before', sa.Float(), nullable=True),
    sa.Column('availability_after', sa.Float(), nullable=True),
    sa.Column('cause', sa.String(length=40), nullable=True),
    sa.Column('expected_return', sa.DateTime(timezone=True), nullable=True),
    sa.Column('news_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('availability_source', sa.String(length=30), nullable=True),
    sa.Column('materiality', sa.Float(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_avail_player_detected', 'availability_events', ['player_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_availability_events_detected_at'), 'availability_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_availability_events_event_type'), 'availability_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_availability_events_player_id'), 'availability_events', ['player_id'], unique=False)
    op.create_table('player_availability_snapshots',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('chance_field', sa.SmallInteger(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('news_text', sa.Text(), nullable=False),
    sa.Column('now_cost', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['availability_events.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_fpl_entry_id'), 'alerts', ['fpl_entry_id'], unique=False)
    op.create_index('ix_alerts_manager_created', 'alerts', ['fpl_entry_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index('ix_alerts_manager_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_fpl_entry_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('player_availability_snapshots')
    op.drop_index(op.f('ix_availability_events_player_id'), table_name='availability_events')
    op.drop_index(op.f('ix_availability_events_event_type'), table_name='availability_events')
    op.drop_index(op.f('ix_availability_events_detected_at'), table_name='availability_events')
    op.drop_index('ix_avail_player_detected', table_name='availability_events')
    op.drop_table('availability_events')
    # ### end Alembic commands ###
